
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("31d17c5e-3cfc-43c7-bc03-cbb4275d1e9a")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class archisof_tbm_regEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new archisof_tbm_regEntities object using the connection string found in the 'archisof_tbm_regEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=archisof_tbm_regEntities", "archisof_tbm_regEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new archisof_tbm_regEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "archisof_tbm_regEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new archisof_tbm_regEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "archisof_tbm_regEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblRegistrationsOEMs() As ObjectSet(Of tblRegistrationsOEM)
        Get
            If (_tblRegistrationsOEMs Is Nothing) Then
                _tblRegistrationsOEMs = MyBase.CreateObjectSet(Of tblRegistrationsOEM)("tblRegistrationsOEMs")
            End If
            Return _tblRegistrationsOEMs
        End Get
    End Property

    Private _tblRegistrationsOEMs As ObjectSet(Of tblRegistrationsOEM)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblUsesOEMs() As ObjectSet(Of tblUsesOEM)
        Get
            If (_tblUsesOEMs Is Nothing) Then
                _tblUsesOEMs = MyBase.CreateObjectSet(Of tblUsesOEM)("tblUsesOEMs")
            End If
            Return _tblUsesOEMs
        End Get
    End Property

    Private _tblUsesOEMs As ObjectSet(Of tblUsesOEM)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblRegistrationsOEMs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblRegistrationsOEMs(ByVal tblRegistrationsOEM As tblRegistrationsOEM)
        MyBase.AddObject("tblRegistrationsOEMs", tblRegistrationsOEM)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblUsesOEMs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblUsesOEMs(ByVal tblUsesOEM As tblUsesOEM)
        MyBase.AddObject("tblUsesOEMs", tblUsesOEM)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="archisof_tbm_regModel", Name:="tblRegistrationsOEM")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblRegistrationsOEM
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblRegistrationsOEM object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreatetblRegistrationsOEM(id As Global.System.Int64) As tblRegistrationsOEM
        Dim tblRegistrationsOEM as tblRegistrationsOEM = New tblRegistrationsOEM
        tblRegistrationsOEM.ID = id
        Return tblRegistrationsOEM
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Title() As Global.System.String
        Get
            Return _Title
        End Get
        Set
            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property

    Private _Title As Global.System.String
    Private Partial Sub OnTitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FName() As Global.System.String
        Get
            Return _FName
        End Get
        Set
            OnFNameChanging(value)
            ReportPropertyChanging("FName")
            _FName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FName")
            OnFNameChanged()
        End Set
    End Property

    Private _FName As Global.System.String
    Private Partial Sub OnFNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LName() As Global.System.String
        Get
            Return _LName
        End Get
        Set
            OnLNameChanging(value)
            ReportPropertyChanging("LName")
            _LName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LName")
            OnLNameChanged()
        End Set
    End Property

    Private _LName As Global.System.String
    Private Partial Sub OnLNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Company() As Global.System.String
        Get
            Return _Company
        End Get
        Set
            OnCompanyChanging(value)
            ReportPropertyChanging("Company")
            _Company = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Company")
            OnCompanyChanged()
        End Set
    End Property

    Private _Company As Global.System.String
    Private Partial Sub OnCompanyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCompanyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Add1() As Global.System.String
        Get
            Return _Add1
        End Get
        Set
            OnAdd1Changing(value)
            ReportPropertyChanging("Add1")
            _Add1 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Add1")
            OnAdd1Changed()
        End Set
    End Property

    Private _Add1 As Global.System.String
    Private Partial Sub OnAdd1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAdd1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Add2() As Global.System.String
        Get
            Return _Add2
        End Get
        Set
            OnAdd2Changing(value)
            ReportPropertyChanging("Add2")
            _Add2 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Add2")
            OnAdd2Changed()
        End Set
    End Property

    Private _Add2 As Global.System.String
    Private Partial Sub OnAdd2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAdd2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Add3() As Global.System.String
        Get
            Return _Add3
        End Get
        Set
            OnAdd3Changing(value)
            ReportPropertyChanging("Add3")
            _Add3 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Add3")
            OnAdd3Changed()
        End Set
    End Property

    Private _Add3 As Global.System.String
    Private Partial Sub OnAdd3Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAdd3Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Add4() As Global.System.String
        Get
            Return _Add4
        End Get
        Set
            OnAdd4Changing(value)
            ReportPropertyChanging("Add4")
            _Add4 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Add4")
            OnAdd4Changed()
        End Set
    End Property

    Private _Add4 As Global.System.String
    Private Partial Sub OnAdd4Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAdd4Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Add5() As Global.System.String
        Get
            Return _Add5
        End Get
        Set
            OnAdd5Changing(value)
            ReportPropertyChanging("Add5")
            _Add5 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Add5")
            OnAdd5Changed()
        End Set
    End Property

    Private _Add5 As Global.System.String
    Private Partial Sub OnAdd5Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAdd5Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Add6() As Global.System.String
        Get
            Return _Add6
        End Get
        Set
            OnAdd6Changing(value)
            ReportPropertyChanging("Add6")
            _Add6 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Add6")
            OnAdd6Changed()
        End Set
    End Property

    Private _Add6 As Global.System.String
    Private Partial Sub OnAdd6Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAdd6Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IP() As Global.System.String
        Get
            Return _IP
        End Get
        Set
            OnIPChanging(value)
            ReportPropertyChanging("IP")
            _IP = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("IP")
            OnIPChanged()
        End Set
    End Property

    Private _IP As Global.System.String
    Private Partial Sub OnIPChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIPChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property QTY() As Nullable(Of Global.System.Int32)
        Get
            Return _QTY
        End Get
        Set
            OnQTYChanging(value)
            ReportPropertyChanging("QTY")
            _QTY = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("QTY")
            OnQTYChanged()
        End Set
    End Property

    Private _QTY As Nullable(Of Global.System.Int32)
    Private Partial Sub OnQTYChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnQTYChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserID() As Global.System.String
        Get
            Return _UserID
        End Get
        Set
            OnUserIDChanging(value)
            ReportPropertyChanging("UserID")
            _UserID = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UserID")
            OnUserIDChanged()
        End Set
    End Property

    Private _UserID As Global.System.String
    Private Partial Sub OnUserIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RegKey() As Global.System.String
        Get
            Return _RegKey
        End Get
        Set
            OnRegKeyChanging(value)
            ReportPropertyChanging("RegKey")
            _RegKey = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RegKey")
            OnRegKeyChanged()
        End Set
    End Property

    Private _RegKey As Global.System.String
    Private Partial Sub OnRegKeyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRegKeyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OrderDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _OrderDate
        End Get
        Set
            OnOrderDateChanging(value)
            ReportPropertyChanging("OrderDate")
            _OrderDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OrderDate")
            OnOrderDateChanged()
        End Set
    End Property

    Private _OrderDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnOrderDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnOrderDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int64
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int64
    Private Partial Sub OnIDChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="archisof_tbm_regModel", Name:="tblUsesOEM")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblUsesOEM
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblUsesOEM object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreatetblUsesOEM(id As Global.System.Int64) As tblUsesOEM
        Dim tblUsesOEM as tblUsesOEM = New tblUsesOEM
        tblUsesOEM.ID = id
        Return tblUsesOEM
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property AppVersion() As Global.System.String
        Get
            Return _AppVersion
        End Get
        Set
            OnAppVersionChanging(value)
            ReportPropertyChanging("AppVersion")
            _AppVersion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("AppVersion")
            OnAppVersionChanged()
        End Set
    End Property

    Private _AppVersion As Global.System.String
    Private Partial Sub OnAppVersionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAppVersionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IP() As Global.System.String
        Get
            Return _IP
        End Get
        Set
            OnIPChanging(value)
            ReportPropertyChanging("IP")
            _IP = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("IP")
            OnIPChanged()
        End Set
    End Property

    Private _IP As Global.System.String
    Private Partial Sub OnIPChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIPChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ComputerName() As Global.System.String
        Get
            Return _ComputerName
        End Get
        Set
            OnComputerNameChanging(value)
            ReportPropertyChanging("ComputerName")
            _ComputerName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ComputerName")
            OnComputerNameChanged()
        End Set
    End Property

    Private _ComputerName As Global.System.String
    Private Partial Sub OnComputerNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnComputerNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserID() As Global.System.String
        Get
            Return _UserID
        End Get
        Set
            OnUserIDChanging(value)
            ReportPropertyChanging("UserID")
            _UserID = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UserID")
            OnUserIDChanged()
        End Set
    End Property

    Private _UserID As Global.System.String
    Private Partial Sub OnUserIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RegKey() As Global.System.String
        Get
            Return _RegKey
        End Get
        Set
            OnRegKeyChanging(value)
            ReportPropertyChanging("RegKey")
            _RegKey = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RegKey")
            OnRegKeyChanged()
        End Set
    End Property

    Private _RegKey As Global.System.String
    Private Partial Sub OnRegKeyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRegKeyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property QTY() As Nullable(Of Global.System.Int32)
        Get
            Return _QTY
        End Get
        Set
            OnQTYChanging(value)
            ReportPropertyChanging("QTY")
            _QTY = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("QTY")
            OnQTYChanged()
        End Set
    End Property

    Private _QTY As Nullable(Of Global.System.Int32)
    Private Partial Sub OnQTYChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnQTYChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateChecked() As Nullable(Of Global.System.DateTime)
        Get
            Return _DateChecked
        End Get
        Set
            OnDateCheckedChanging(value)
            ReportPropertyChanging("DateChecked")
            _DateChecked = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateChecked")
            OnDateCheckedChanged()
        End Set
    End Property

    Private _DateChecked As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDateCheckedChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDateCheckedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int64
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int64
    Private Partial Sub OnIDChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    #End Region
End Class

#End Region

