'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module ResourceStrings
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("eMailManager.ResourceStrings", GetType(ResourceStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to batch file mode.
        '''</summary>
        Friend ReadOnly Property BatchFileMode() As String
            Get
                Return ResourceManager.GetString("BatchFileMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email messages in this folder have been filed to the file system. Delete these messages regularly to keep your mailbox small..
        '''</summary>
        Friend ReadOnly Property DeletedItemsDescription() As String
            Get
                Return ResourceManager.GetString("DeletedItemsDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter description for save location:.
        '''</summary>
        Friend ReadOnly Property LocationDescription() As String
            Get
                Return ResourceManager.GetString("LocationDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About....
        '''</summary>
        Friend ReadOnly Property MenuAbout() As String
            Get
                Return ResourceManager.GetString("MenuAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear deleted items.
        '''</summary>
        Friend ReadOnly Property MenuClearDeletedItems() As String
            Get
                Return ResourceManager.GetString("MenuClearDeletedItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Folder....
        '''</summary>
        Friend ReadOnly Property MenuFileFolder() As String
            Get
                Return ResourceManager.GetString("MenuFileFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Message....
        '''</summary>
        Friend ReadOnly Property MenuFileMessage() As String
            Get
                Return ResourceManager.GetString("MenuFileMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search....
        '''</summary>
        Friend ReadOnly Property MenuSearch() As String
            Get
                Return ResourceManager.GetString("MenuSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings....
        '''</summary>
        Friend ReadOnly Property MenuSettings() As String
            Get
                Return ResourceManager.GetString("MenuSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update....
        '''</summary>
        Friend ReadOnly Property MenuUpdate() As String
            Get
                Return ResourceManager.GetString("MenuUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the item that you want to save..
        '''</summary>
        Friend ReadOnly Property Message001() As String
            Get
                Return ResourceManager.GetString("Message001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like empty the &apos;Deleted Items (eMail Manager)&apos; folder?.
        '''</summary>
        Friend ReadOnly Property Message002() As String
            Get
                Return ResourceManager.GetString("Message002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File all messages in .
        '''</summary>
        Friend ReadOnly Property Message003() As String
            Get
                Return ResourceManager.GetString("Message003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to save your attachments to the same folder as the .msg file?.
        '''</summary>
        Friend ReadOnly Property Message004() As String
            Get
                Return ResourceManager.GetString("Message004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please check you have selected the correct location type (File system folder or Outlook folder) for the selected save location. Also check you have write permissions on the target folder and also that you have permission to move emails in Outlook.
        '''</summary>
        Friend ReadOnly Property Message005() As String
            Get
                Return ResourceManager.GetString("Message005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose a location to save attachments..
        '''</summary>
        Friend ReadOnly Property Message006() As String
            Get
                Return ResourceManager.GetString("Message006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank you for purchasing this software. Unfortunately there seems to be a problem registering your software. Please check you have entered the correct information and try again. If you believe this is an error please email support@archisoft.co.uk for a resolution..
        '''</summary>
        Friend ReadOnly Property Message007() As String
            Get
                Return ResourceManager.GetString("Message007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to searching message files.
        '''</summary>
        Friend ReadOnly Property Message008() As String
            Get
                Return ResourceManager.GetString("Message008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the item that you want to save..
        '''</summary>
        Friend ReadOnly Property Message009() As String
            Get
                Return ResourceManager.GetString("Message009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The eMail Scheduler addin does not appear to be installed.
        '''</summary>
        Friend ReadOnly Property Message010() As String
            Get
                Return ResourceManager.GetString("Message010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please wait! Gathering all *.MSG files to search.
        '''</summary>
        Friend ReadOnly Property Message011() As String
            Get
                Return ResourceManager.GetString("Message011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finshed gathering *.MSG files.
        '''</summary>
        Friend ReadOnly Property Message012() As String
            Get
                Return ResourceManager.GetString("Message012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use Escape key to cancel loading messages.
        '''</summary>
        Friend ReadOnly Property Message013() As String
            Get
                Return ResourceManager.GetString("Message013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This change will not take place until you restart Outlook and eMail Manager.
        '''</summary>
        Friend ReadOnly Property Message014() As String
            Get
                Return ResourceManager.GetString("Message014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detailed Search.
        '''</summary>
        Friend ReadOnly Property SearchTitle001() As String
            Get
                Return ResourceManager.GetString("SearchTitle001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detailed Search (slow method).
        '''</summary>
        Friend ReadOnly Property SearchTitle002() As String
            Get
                Return ResourceManager.GetString("SearchTitle002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a folder to search for *.msg files.
        '''</summary>
        Friend ReadOnly Property SearchTitle003() As String
            Get
                Return ResourceManager.GetString("SearchTitle003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finished.
        '''</summary>
        Friend ReadOnly Property sFINISHED() As String
            Get
                Return ResourceManager.GetString("sFINISHED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SEARCH.
        '''</summary>
        Friend ReadOnly Property sSEARCH() As String
            Get
                Return ResourceManager.GetString("sSEARCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STOP.
        '''</summary>
        Friend ReadOnly Property sSTOP() As String
            Get
                Return ResourceManager.GetString("sSTOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File message (any attachments remain embedded).
        '''</summary>
        Friend ReadOnly Property WorkFlow01() As String
            Get
                Return ResourceManager.GetString("WorkFlow01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File message and attachments separately (save the attachments in file system).
        '''</summary>
        Friend ReadOnly Property WorkFlow02() As String
            Get
                Return ResourceManager.GetString("WorkFlow02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File message and attachments separately (keep a copy of attachments in message).
        '''</summary>
        Friend ReadOnly Property WorkFlow03() As String
            Get
                Return ResourceManager.GetString("WorkFlow03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File message and strip attachments from the message (removes the attachments).
        '''</summary>
        Friend ReadOnly Property WorkFlow03a() As String
            Get
                Return ResourceManager.GetString("WorkFlow03a", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
