//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMailManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eMailManager.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch file mode.
        /// </summary>
        internal static string BatchFileMode {
            get {
                return ResourceManager.GetString("BatchFileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop monitoring.
        /// </summary>
        internal static string CancelMonitoringCaption {
            get {
                return ResourceManager.GetString("CancelMonitoringCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cancelled saving the last 5 sent messages. Would you like to stop monitoring sent emails until Outlook is restarted?.
        /// </summary>
        internal static string CancelMonitoringMessage {
            get {
                return ResourceManager.GetString("CancelMonitoringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email messages in this folder have been filed to the file system. Delete these messages regularly to keep your mailbox small..
        /// </summary>
        internal static string DeletedItemsDescription {
            get {
                return ResourceManager.GetString("DeletedItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Message....
        /// </summary>
        internal static string MenuFileMessage {
            get {
                return ResourceManager.GetString("MenuFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the item that you want to save..
        /// </summary>
        internal static string Message001 {
            get {
                return ResourceManager.GetString("Message001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like empty the &apos;Deleted Items (eMail Manager)&apos; folder?.
        /// </summary>
        internal static string Message002 {
            get {
                return ResourceManager.GetString("Message002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File all messages in.
        /// </summary>
        internal static string Message003 {
            get {
                return ResourceManager.GetString("Message003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your attachments to the same folder as the .msg file?.
        /// </summary>
        internal static string Message004 {
            get {
                return ResourceManager.GetString("Message004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check you have selected the correct location type (File system folder or Outlook folder) for the selected save location. Also check you have write permissions on the target folder and also that you have permission to move emails in Outlook.
        /// </summary>
        internal static string Message005 {
            get {
                return ResourceManager.GetString("Message005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a location to save attachments..
        /// </summary>
        internal static string Message006 {
            get {
                return ResourceManager.GetString("Message006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not appear to exist in the file system.
        /// </summary>
        internal static string Message007 {
            get {
                return ResourceManager.GetString("Message007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching message files.
        /// </summary>
        internal static string Message008 {
            get {
                return ResourceManager.GetString("Message008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the item that you want to save..
        /// </summary>
        internal static string Message009 {
            get {
                return ResourceManager.GetString("Message009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Message010 {
            get {
                return ResourceManager.GetString("Message010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Message011 {
            get {
                return ResourceManager.GetString("Message011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Message012 {
            get {
                return ResourceManager.GetString("Message012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Message013 {
            get {
                return ResourceManager.GetString("Message013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will not take place until you restart Outlook and eMail Manager.
        /// </summary>
        internal static string Message014 {
            get {
                return ResourceManager.GetString("Message014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File message (any attachments remain embedded).
        /// </summary>
        internal static string WorkFlow01 {
            get {
                return ResourceManager.GetString("WorkFlow01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File message and attachments separately (keep a copy of attachments in message).
        /// </summary>
        internal static string WorkFlow02 {
            get {
                return ResourceManager.GetString("WorkFlow02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File message and strip attachments from the message (removes and saves the attachments in file systes).
        /// </summary>
        internal static string WorkFlow03 {
            get {
                return ResourceManager.GetString("WorkFlow03", resourceCulture);
            }
        }
    }
}
