'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18047
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.keygenSoap")>  _
    Public Interface keygenSoap
        
        'CODEGEN: Generating message contract since element name UserID from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/KeyGen", ReplyAction:="*")>  _
        Function KeyGen(ByVal request As ServiceReference1.KeyGenRequest) As ServiceReference1.KeyGenResponse
        
        'CODEGEN: Generating message contract since element name NewGUIDResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/NewGUID", ReplyAction:="*")>  _
        Function NewGUID(ByVal request As ServiceReference1.NewGUIDRequest) As ServiceReference1.NewGUIDResponse
        
        'CODEGEN: Generating message contract since element name sIP from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RecordUsage", ReplyAction:="*")>  _
        Function RecordUsage(ByVal request As ServiceReference1.RecordUsageRequest) As ServiceReference1.RecordUsageResponse
        
        'CODEGEN: Generating message contract since element name sIP from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RecordUsageA", ReplyAction:="*")>  _
        Function RecordUsageA(ByVal request As ServiceReference1.RecordUsageARequest) As ServiceReference1.RecordUsageAResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class KeyGenRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="KeyGen", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.KeyGenRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.KeyGenRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class KeyGenRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Qty As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserID As String, ByVal Qty As Integer)
            MyBase.New
            Me.UserID = UserID
            Me.Qty = Qty
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class KeyGenResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="KeyGenResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.KeyGenResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.KeyGenResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class KeyGenResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public KeyGenResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal KeyGenResult As String)
            MyBase.New
            Me.KeyGenResult = KeyGenResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class NewGUIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="NewGUID", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.NewGUIDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.NewGUIDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class NewGUIDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class NewGUIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="NewGUIDResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.NewGUIDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.NewGUIDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class NewGUIDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public NewGUIDResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal NewGUIDResult As String)
            MyBase.New
            Me.NewGUIDResult = NewGUIDResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecordUsageRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecordUsage", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.RecordUsageRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.RecordUsageRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RecordUsageRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sIP As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public sComputerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public sUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public sRegKey As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public iQty As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sIP As String, ByVal sComputerName As String, ByVal sUserID As String, ByVal sRegKey As String, ByVal iQty As Integer)
            MyBase.New
            Me.sIP = sIP
            Me.sComputerName = sComputerName
            Me.sUserID = sUserID
            Me.sRegKey = sRegKey
            Me.iQty = iQty
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecordUsageResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecordUsageResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.RecordUsageResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.RecordUsageResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class RecordUsageResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecordUsageARequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecordUsageA", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.RecordUsageARequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.RecordUsageARequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RecordUsageARequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sIP As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public sComputerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public sUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public sRegKey As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public iQty As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public sAppVersion As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sIP As String, ByVal sComputerName As String, ByVal sUserID As String, ByVal sRegKey As String, ByVal iQty As Integer, ByVal sAppVersion As String)
            MyBase.New
            Me.sIP = sIP
            Me.sComputerName = sComputerName
            Me.sUserID = sUserID
            Me.sRegKey = sRegKey
            Me.iQty = iQty
            Me.sAppVersion = sAppVersion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecordUsageAResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecordUsageAResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.RecordUsageAResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.RecordUsageAResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class RecordUsageAResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface keygenSoapChannel
        Inherits ServiceReference1.keygenSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class keygenSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.keygenSoap)
        Implements ServiceReference1.keygenSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_keygenSoap_KeyGen(ByVal request As ServiceReference1.KeyGenRequest) As ServiceReference1.KeyGenResponse Implements ServiceReference1.keygenSoap.KeyGen
            Return MyBase.Channel.KeyGen(request)
        End Function
        
        Public Function KeyGen(ByVal UserID As String, ByVal Qty As Integer) As String
            Dim inValue As ServiceReference1.KeyGenRequest = New ServiceReference1.KeyGenRequest()
            inValue.Body = New ServiceReference1.KeyGenRequestBody()
            inValue.Body.UserID = UserID
            inValue.Body.Qty = Qty
            Dim retVal As ServiceReference1.KeyGenResponse = CType(Me,ServiceReference1.keygenSoap).KeyGen(inValue)
            Return retVal.Body.KeyGenResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_keygenSoap_NewGUID(ByVal request As ServiceReference1.NewGUIDRequest) As ServiceReference1.NewGUIDResponse Implements ServiceReference1.keygenSoap.NewGUID
            Return MyBase.Channel.NewGUID(request)
        End Function
        
        Public Function NewGUID() As String
            Dim inValue As ServiceReference1.NewGUIDRequest = New ServiceReference1.NewGUIDRequest()
            inValue.Body = New ServiceReference1.NewGUIDRequestBody()
            Dim retVal As ServiceReference1.NewGUIDResponse = CType(Me,ServiceReference1.keygenSoap).NewGUID(inValue)
            Return retVal.Body.NewGUIDResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_keygenSoap_RecordUsage(ByVal request As ServiceReference1.RecordUsageRequest) As ServiceReference1.RecordUsageResponse Implements ServiceReference1.keygenSoap.RecordUsage
            Return MyBase.Channel.RecordUsage(request)
        End Function
        
        Public Sub RecordUsage(ByVal sIP As String, ByVal sComputerName As String, ByVal sUserID As String, ByVal sRegKey As String, ByVal iQty As Integer)
            Dim inValue As ServiceReference1.RecordUsageRequest = New ServiceReference1.RecordUsageRequest()
            inValue.Body = New ServiceReference1.RecordUsageRequestBody()
            inValue.Body.sIP = sIP
            inValue.Body.sComputerName = sComputerName
            inValue.Body.sUserID = sUserID
            inValue.Body.sRegKey = sRegKey
            inValue.Body.iQty = iQty
            Dim retVal As ServiceReference1.RecordUsageResponse = CType(Me,ServiceReference1.keygenSoap).RecordUsage(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_keygenSoap_RecordUsageA(ByVal request As ServiceReference1.RecordUsageARequest) As ServiceReference1.RecordUsageAResponse Implements ServiceReference1.keygenSoap.RecordUsageA
            Return MyBase.Channel.RecordUsageA(request)
        End Function
        
        Public Sub RecordUsageA(ByVal sIP As String, ByVal sComputerName As String, ByVal sUserID As String, ByVal sRegKey As String, ByVal iQty As Integer, ByVal sAppVersion As String)
            Dim inValue As ServiceReference1.RecordUsageARequest = New ServiceReference1.RecordUsageARequest()
            inValue.Body = New ServiceReference1.RecordUsageARequestBody()
            inValue.Body.sIP = sIP
            inValue.Body.sComputerName = sComputerName
            inValue.Body.sUserID = sUserID
            inValue.Body.sRegKey = sRegKey
            inValue.Body.iQty = iQty
            inValue.Body.sAppVersion = sAppVersion
            Dim retVal As ServiceReference1.RecordUsageAResponse = CType(Me,ServiceReference1.keygenSoap).RecordUsageA(inValue)
        End Sub
    End Class
End Namespace
